//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeX.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeX.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeX.
        /// </summary>
        public static string all_application_name {
            get {
                return ResourceManager.GetString("all_application_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialog_cancel {
            get {
                return ResourceManager.GetString("dialog_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialog_ok {
            get {
                return ResourceManager.GetString("dialog_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string error_account_bad_password {
            get {
                return ResourceManager.GetString("error_account_bad_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist..
        /// </summary>
        public static string error_account_bad_username {
            get {
                return ResourceManager.GetString("error_account_bad_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name is required..
        /// </summary>
        public static string error_required_name_family {
            get {
                return ResourceManager.GetString("error_required_name_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name is required..
        /// </summary>
        public static string error_required_name_given {
            get {
                return ResourceManager.GetString("error_required_name_given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string error_required_name_user {
            get {
                return ResourceManager.GetString("error_required_name_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string error_required_password {
            get {
                return ResourceManager.GetString("error_required_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main phone number is required..
        /// </summary>
        public static string error_required_phonemain {
            get {
                return ResourceManager.GetString("error_required_phonemain", resourceCulture);
            }
        }
    }
}
